version: '3'
services:
  #Redis
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    tty: true
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./cache-redis:/data
    networks:
      - app-network

#Networks
networks:
  app-network:
    name: app-network
    driver: bridge
